# Generated by Django 2.2 on 2021-05-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homely_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de movimiento')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('recurrence', models.IntegerField(blank=True, verbose_name='Días de recurrencia')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de receta')),
                ('image', models.ImageField(blank=True, upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='SmartDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de objeto inteligente')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homely_app.Room')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('liq_edible', 'Líquido comestible'), ('liq_cleaning', 'Líquido de limpieza'), ('sol_unit_edible', 'Sólido comestible por unidades'), ('sol_weight_edible', 'Sólido comestible por peso'), ('sol_cleaning', 'Sólidos para limpieza'), ('supply', 'Suministro'), ('consumable', 'Consumible genérico'), ('tool', 'Herramienta'), ('furniture', 'Mobiliario'), ('other', 'Otros')], default='other', max_length=60, verbose_name='Tipo de objeto'),
        ),
        migrations.CreateModel(
            name='SmartMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de método')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homely_app.SmartDevice')),
            ],
        ),
    ]
