# Generated by Django 2.2 on 2021-05-24 17:16

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('homely_app', '0005_auto_20210516_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='process',
            field=martor.models.MartorField(blank=True, verbose_name='Pasos de la receta'),
        ),
        migrations.CreateModel(
            name='RecipeRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homely_app.Item')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasableItemVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha de transacción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cantidad')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relItem', to='homely_app.PurchasableItem')),
            ],
        ),
    ]
