# Generated by Django 2.2 on 2021-05-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homely_app', '0006_auto_20210524_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasableitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasableitem',
            name='storageSpace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homely_app.Room', verbose_name='Lugar de almacenaje'),
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad'),
            preserve_default=False,
        ),
    ]
