# Generated by Django 2.2 on 2021-05-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homely_app', '0007_auto_20210524_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasableitem',
            name='isWishlist',
            field=models.BooleanField(default=False, verbose_name='¿Es un elemento de lista de deseos?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('liq_edible', 'Líquido comestible'), ('liq_cleaning', 'Líquido de limpieza'), ('sol_unit_edible', 'Sólido comestible por unidades'), ('sol_weight_edible', 'Sólido comestible por peso'), ('sol_cleaning', 'Sólidos para limpieza'), ('supply', 'Suministro'), ('consumable', 'Consumible genérico'), ('tool', 'Herramienta'), ('furniture', 'Mobiliario'), ('dishware', 'Vajilla'), ('electronics', 'Electrónica'), ('other', 'Otros')], default='other', max_length=60, verbose_name='Tipo de objeto'),
        ),
    ]
