# Generated by Django 2.2 on 2021-05-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homely_app', '0009_auto_20210527_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasableitemvariation',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('CONSUMPTION', 'Consumption'), ('THROW_AWAY', 'Throw away'), ('REPLACEMENT', 'Replacement'), ('REFILLMENT', 'Refillment')], default='PURCHASE', max_length=32),
            preserve_default=False,
        ),
    ]
