# Generated by Django 2.2 on 2021-05-27 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homely_app', '0010_purchasableitemvariation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagespace',
            name='parentStorageSpace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homely_app.StorageSpace'),
        ),
    ]
