# Generated by Django 2.2 on 2021-05-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homely_app', '0011_storagespace_parentstoragespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='purchasableitem',
            name='barCode',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='purchasableitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='purchasableItems/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='smartdevice',
            name='image',
            field=models.ImageField(blank=True, upload_to='smartDevices/'),
        ),
        migrations.AddField(
            model_name='storagespace',
            name='image',
            field=models.ImageField(blank=True, upload_to='storageSpaces/'),
        ),
    ]
