# Generated by Django 2.2 on 2021-05-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homely_app', '0012_auto_20210527_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespace',
            name='parentStorageSpace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homely_app.StorageSpace'),
        ),
    ]
