# Generated by Django 2.2 on 2021-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homely_app', '0013_auto_20210527_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=64, verbose_name='Texto de etiqueta')),
            ],
        ),
    ]
